name: Hacker News Validation

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:       # Allow manual runs

jobs:
  validate-hn-sorting:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Build Docker image
        run: docker build -t hn-validation .
        
      - name: Run validation
        run: docker run --name hn-validator hn-validation
        
      - name: Copy report from container
        run: |
          mkdir -p ./reports
          docker cp hn-validator:/app/reports/ ./reports/
        
      - name: Upload report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: validation-reports
          path: reports/